#!/bin/bash

datelog=`date '+%d/%m/%Y  %H:%M:%S'`
echo $datelog >> /var/log/update_script.log
echo -e "\n" >> /var/log/update.script
apt-get update && apt-get dist-upgrade >> /var/log/update_script.log
echo -e "\n" >> /var/log/update_script.log
